Comunication_LTD/Comunication_LTD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")), # That's the problem with moving to the page: 'accounts/password_change/done/'
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r'^accounts/login/reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="reset_password"),
    url(r'^password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    url(r'^reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    url(r'^password_change/', auth_views.PasswordChangeView.as_view(template_name="accounts/change_password.html"), name="password_change"),
    url(r'^accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),


]

#     url(r'^password_reset/confrim/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),

# url(r'^password_change/done/', auth_views.PasswordChangeDoneView.as_view(
#                               template_name="accounts/password_change_done.html"), name='password_change_done'),

Comunication_LTD/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

Comunication_LTD/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

Comunication_LTD/groups/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

Comunication_LTD/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Group, GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already groups member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now groups member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

Comunication_LTD/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

Comunication_LTD/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1>{{group.name}}</h1>
<h2> Member Count: {{group.members.count}}</h2>

  <div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

{% endblock %}

Comunication_LTD/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

Comunication_LTD/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
			<h2>Internet Surfing Packages</h2>

	</div>
	{% if user.is_authenticated %}
	<!-- <groups href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Package!</groups> -->
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
 <div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}