Comunication_LTD/Comunication_LTD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")), # That's the problem with moving to the page: 'accounts/password_change/done/'
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r'^accounts/login/reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="reset_password"),
    url(r'^password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    url(r'^reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    url(r'^password_change/', auth_views.PasswordChangeView.as_view(template_name="accounts/change_password.html"), name="password_change"),
    url(r'^accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),


]

#     url(r'^password_reset/confrim/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),

# url(r'^password_change/done/', auth_views.PasswordChangeDoneView.as_view(
#                               template_name="accounts/password_change_done.html"), name='password_change_done'),

Comunication_LTD/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

Comunication_LTD/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

import misaka

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

Comunication_LTD/posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

Comunication_LTD/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

Comunication_LTD/posts/templates/posts/_post.html
<div class="post media">
	<h3>{{ post.message_html|safe }}</h3>
	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>




		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

Comunication_LTD/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

Comunication_LTD/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

Comunication_LTD/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

Comunication_LTD/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

Comunication_LTD/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
			



		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

Comunication_LTD/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}