Comunication_LTD/Comunication_LTD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")), # That's the problem with moving to the page: 'accounts/password_change/done/'
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r'^accounts/login/reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="reset_password"),
    url(r'^password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    url(r'^reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    url(r'^password_change/', auth_views.PasswordChangeView.as_view(template_name="accounts/change_password.html"), name="password_change"),
    url(r'^accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name="password_change_done"),


]

#     url(r'^password_reset/confrim/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name="password_reset_confirm"),

# url(r'^password_change/done/', auth_views.PasswordChangeDoneView.as_view(
#                               template_name="accounts/password_change_done.html"), name='password_change_done'),

Comunication_LTD/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"password/$", views.ChangePassword.as_view(), name="change"),     # Do nothing I think

]

Comunication_LTD/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

Comunication_LTD/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Comunication_LTD</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Comunication_LTD</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <!--<li><groups href="{% url 'posts:create' %}" class="btn btn-simple">Internet Surfing Packages</groups></li>-->
                      <li><a href="/password_change" class="btn btn-simple">Change Password</a></li>
                      <!--<li><groups href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</groups></li>-->
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Internet Surfing Packages</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

Comunication_LTD/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Comunication_LTD!</h1>
    <h2>The best internet surfing packages deals!</h2>
    <h3>Login or Sign-up for details</h3>


{% endblock %}

Comunication_LTD/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2>
    Welcome back @{{user.username }}
  </h2>

  <h2><a href="{% url 'groups:all'%}">Go To Internet Surfing Packages</a></h2>


</div>




{% endblock %}

Comunication_LTD/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}